name: API Check

on:
  workflow_dispatch:     # manuell auslösbar
  schedule:
    - cron: '0 9 * * 1'  # jeden Montag um 09:00 UTC

jobs:
  create-doc-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install required Python packages
        run: pip install requests

      - name: Generate docs_missing.json
        run: python .github/_scripts/checks/endpoints.py

      - name: Create GitHub Issues for undocumented endpoints
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: python .github/_scripts/generate-issues.py ./github/.json